version: '3.7'
name: team4est-docker

services:
  auth_service_postgres:
    image: postgres:latest
    container_name: auth_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth-service
    ports:
      - 5432:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data

  category_service_mongodb:
    image: mongo
    container_name: category_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/var/lib/mongodb/data

volumes:
  pgdbdata:
    driver: local
  mongodbdata:
    driver: local
