logging:
  level:
    org:
      springframework:
        security: INFO
spring:
  config:
    import: env.properties
  datasource:
    username: ${AUTH_SERIVCE_DB_USERNAME}
    url: ${AUTH_SERIVCE_DB_URL}
    password: ${AUTH_SERIVCE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: auth-service
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: 'true'
server:
  port: '0'
