eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: 'true'
spring:
  config:
    import: env.properties
  application:
    name: team-service
  data:
    mongodb:
      uri: ${TEAM_SERIVCE_DB_URL}
server:
  port: 0
