eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: 'true'
spring:
  config:
    import: env.properties
  application:
    name: user-service
  data:
    mongodb:
      uri: ${USER_SERIVCE_DB_URL}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    template:
      default-topic: ${KAFKA_TOPIC}
    consumer:
      properties:
        spring.json.type.mapping: event:com.team4est.*-.events.AccountCreatedEvent
        spring.json.trusted.packages: com.team4est.*-.events.*
server:
  port: 0
